 run "ln -nfs #{shared_path}/config/email.yml #{release_path}/config/email.yml"
 run "ln -nfs #{shared_path}/config/ferret_server.yml #{release_path}/config/ferret_server.yml"
 run "ln -nfs #{shared_path}/config/newrelic.yml #{release_path}/config/newrelic.yml"
 run "ln -nfs #{shared_path}/config/memcached.yml #{release_path}/config/memcached.yml"
 run "ln -nfs #{shared_path}/config/session_secret.yml #{release_path}/config/session_secret.yml"
